### PR TITLE
Added Web part Creation and Tested PnP Template supports updates

### PR DESCRIPTION
**Pull request by Abdullahiibrahimahmed**
Have added: 
1. AddWebPartModernPage.cs that adds modern web part to a page.
2. Test-WebpartUpdate.xml  file that i used when testing PnP update Scenario. i changed Pictures in site Assets and updated!

### CODE REVIEW

**Comment by olemp** [comment]
* We don't want any test assets/files in the codebase
* We don't want to use hardcoded credentials
* It should be under SharePoint
* Take a look at how the other tasks uses the app for auth

**Comment by wobba** [comment]
Adding webpart with code is fine, but just as easy to use a PnP template for this as it's supported.

**Comment by wobba** [comment]
Please fix the code as per comments from Ole. I've reopened the PR for now until changed.

**Comment by olemp** [comment]
> Adding webpart with code is fine, but just as easy to use a PnP template for this as it's supported.

Is the update scenario supported now? Then we wouldn't need this function I guess.

**Comment by wobba** [comment]
@olemp good point.. update is probably not supported, but might not be needed in a provisioning scenario which is the scope for this project. But a nice function to have.

**Comment by olemp** [comment]
This is the related issue: https://github.com/CrayonAS/Cumulus.Monads/issues/16

**Comment by olemp** [comment]
@Abdullahiibrahimahmed I've given you full access. You can now merge this PR.

**Pull request merged**
